config/routes.rb
Rails.application.routes.draw do

  get '/users/info', to: 'users#info'
  post '/users/charge', to: 'users#charge'
  get '/users/cancel_subscription', to: 'users#cancel_subscription'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root to: "home#index"

  resources :publications, only: [:index, :show]

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :subscription

  after_create :create_subscription

  def create_subscription
    Subscription.create(user_id: id) if subscription.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_filter :check_for_subscription, only: :show

  def index
    @publications = Publication.all
  end

  def show
    @publication = Publication.find(params[:id])
  end

  def check_for_subscription
    unless current_user.subscription.active
      flash[:alert] = "You must be subscribed to access this content."
      redirect_to publications_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def info
    @subscription = current_user.subscription
    if @subscription.active
      @stripe_customer = Stripe::Customer.retrieve(@subscription.stripe_user_id)
      @stripe_subscription = @stripe_customer.subscriptions.first
    end
  end

  def cancel_subscription
    @subscription = current_user.subscription
    @stripe_customer = Stripe::Customer.retrieve(@subscription.stripe_user_id)
    @stripe_subscription = @stripe_customer.subscriptions.first

    @stripe_subscription.delete
    current_user.subscription.active = false
    current_user.subscription.save

    redirect_to users_info_path
  end

  def charge
    token = params["stripeToken"]
 
    customer = Stripe::Customer.create(
      source: token,
      plan: 'basic_plan_1',
      email: current_user.email
    )
    current_user.subscription.stripe_user_id = customer.id
    current_user.subscription.active = true
    current_user.subscription.save
    redirect_to users_info_path

    rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to users_info_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SubscriptionApp</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'Publications', publications_path %></li></a>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, users_info_path %></li></a>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.nasignvbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<div class="row db-padding-btm db-attached">
            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                <div class="db-wrapper">
                    <div class="db-pricing-eleven db-bk-color-one">
                        <div class="price">
                            <sup>$</sup>9.99
                                <small>per month</small>
                        </div>
                        <div class="type">
                            BASIC PLAN
                        </div>
                        <ul>

                            <li><i class="glyphicon glyphicon-print"></i>30+ Publications </li>
                            <li><i class="glyphicon glyphicon-trash"></i>Lead Required</li>
                        </ul>
                        <div class="pricing-footer">
                        <%= link_to 'Subscribe', users_info_path, class: "btn db-button-color-square btn-lg" %>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                  <div class="db-wrapper">
                <div class="db-pricing-eleven db-bk-color-two popular">
                    <div class="price">
                        <sup>$</sup>19.99
                                <small>per quarter</small>
                    </div>
                    <div class="type">
                        MEDIUM PLAN
                    </div>
                    <ul>

                        <li><i class="glyphicon glyphicon-print"></i>150+ Publications </li>
                        <li><i class="glyphicon glyphicon-trash"></i>Lead Required</li>
                    </ul>
                    <div class="pricing-footer">
                        <a href="#" class="btn db-button-color-square btn-lg">Subscribe</a>
                    </div>
                </div>
                      </div>
            </div>
            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                  <div class="db-wrapper">
                <div class="db-pricing-eleven db-bk-color-three">
                    <div class="price">
                        <sup>$</sup>49.99
                                <small>per year</small>
                    </div>
                    <div class="type">
                        ADVANCE PLAN
                    </div>
                    <ul>

                        <li><i class="glyphicon glyphicon-print"></i>All Publications </li>
                        <li><i class="glyphicon glyphicon-trash"></i>Lead Required</li>
                    </ul>
                    <div class="pricing-footer">

                        <a href="#" class="btn db-button-color-square btn-lg">Subscribe</a>
                    </div>
                </div>
                      </div>
            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubscriptionApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">  
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_iQhfPUKLSktAqS2v4bwUPUjh');
  </script>
</head>
<body>
  <%= render 'nav' %>
  <div>
        <%if alert && alert.length > 0 then %>
            <div class="alert alert-warning"><%=alert%></div>
        <% end %>
        <%if notice && notice.size > 0 then %>
          <div class="alert alert-success"><%=notice%></div>
        <% end %>
  </div>


<%= yield %>

</body>
</html>

app/views/publications/index.html.erb
<h2>Publications</h2>

<% @publications.each do |publication| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= publication.title %></h3>
    </div>
    <div class="panel-body">
      <p><%= publication.description.html_safe %></p>
      <p><%= publication.file_url %></p>
    </div>
    <div class="panel-footer">
      <%= link_to "View more details", publication_path(publication), class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/publications/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @publication.title %></h3>
  </div>
  <div class="panel-body">
    <p><%= @publication.description.html_safe %></p>
    <p><%= @publication.file_url %></p>
  </div>
</div>

app/views/users/_form.html.erb
<h4>Begin your $9.99 a month subscription</h4>
<form action="/users/charge" method="POST" id="payment-form">
  <span class="payment-errors"></span>

  <div class="row">
    <div class="col-md-6">
      <label>Card Number</label>
      <input class="form-control" type="text" size="20" data-stripe="number" placeholder="4242424242424242"/>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-xs-2">
      <label>CVC</label>
      <input type="text" data-stripe="cvc" class="form-control" placeholder="123">
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-xs-2">
      <label>Expiration</label>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-1">
      <label>MM</label>
      <input type="text" data-stripe="exp-month" class="form-control" placeholder="01">
    </div>
    <div class="col-xs-1">
      <label>YYYY</label>
      <input type="text" data-stripe="exp-year" class="form-control" placeholder="2020">
    </div>
  </div>

  <div class="row">
    <br/><button class="btn btn-primary" type="submit">Create Subscription</button>
  </div>

  <%= token_tag nil %>
</form>

app/views/users/info.html.erb
<div class="container">
  <h3>Account for <%= current_user.email %></h3>
  <% if @subscription.active %>
    <h3>Current plan renews at: <%= Time.at(@stripe_subscription["current_period_end"]).strftime("%D") %></h3>

    <%= link_to "Cancel subscription", users_cancel_subscription_path %>
  <% else %>
    <%= render 'form' %>
  <% end %>
</div>